
name: 'spark_utils_dbt_utils_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    
vars:
  dbt_utils_dispatch_list: ['spark_utils']

models:
  dbt_utils_integration_tests:
    sql:
      # macro doesn't work
      test_get_relations_by_pattern:
        +enabled: false
      test_get_relations_by_prefix_and_union:
        +enabled: false
      # integration test doesn't work
      test_groupby:
        +enabled: false
    
    schema_tests:
      # needs fix in dbt-utils
      test_equal_column_subset:
        +enabled: false
      # integration test doesn't work
      test_recency:
        +enabled: false
        
seeds:
  dbt_utils_integration_tests:
    sql:
      # integration test doesn't work
      +data_get_query_results_as_dict:
        +enabled: false
